[
{"image": "tiktok.png", "name": "TikTok成人版", "url": "https://c75c.pqbraspk.xyz/chan/GS2461/cAsTp"},
{"image": "jmtt.png",   "name": "禁漫天堂", "url": "https://d98a.quafnpc.xyz/chan/jm1300/5rmW"},
{"image": "51dm.png",   "name": "51动漫", "url": "https://6b25.dpnrmwtg.cc/?code=bJMDj&c=18844"},
{"image": "91qy.png",   "name": "91妻友", "url": "https://7dc31.yscidwgd.xyz/aff-cfHS7"},
{"image": "Pornhub.png","name": "PornHub", "url": "https://c35d.bqnaafn.xyz/chan/GS1000/agtRG"},
{"image": "hjllsq.png", "name": "海角乱伦社区", "url": "https://1657.zsfatngo.xyz/aff-ekUuZ"},
{"image": "51pc.png",   "name": "51品茶", "url": "https://691c.krctjym.cc/?code=bqgkF&c=18844"},
{"image": "aiss.png",   "name": "ai色色", "url": "https://aaa7.qjygyeol.cc/aff-JCVd"},
{"image": "91dsp.png",  "name": "91短视频", "url": "https://f740a.nonvfflc.xyz/chan-5028/aff-mhY87"},
{"image": "91porn.png", "name": "91PORN", "url": "https://b91d.vyqndtf.xyz/chan/GS0710/nN9s"},
{"image": "awjq.png",   "name": "暗网禁区", "url": "https://6f0c.atoofstm.xyz/aff-dHXe9"},
{"image": "dymax.png",  "name": "抖音Max", "url": "https://0398.sxxvxzar.xyz/chan/max1559/KD4j"},
{"image": "pilipili.png", "name": "pilipili(二次元)", "url": "https://90a.cfvsieyn.cc/?code=arGSB&c=18844"},
{"image": "ttt.png", "name": "汤头条", "url": "https://98ba.crtbcsrd.cc/chan/a15235/jxTf3"},
{"image": "xnjlb.png", "name": "gay男同乐园", "url": "https://4d555.waxjish.xyz/chan/xb3859/czTvz"},
{"image": "youtube.png", "name": "YouTube成人版", "url": "https://d85d.gjjrfzvn.cc/aff-7z3y"},
{"image": "50dh.png", "name": "50度灰", "url": "https://f1098.abuielw.xyz/chan/h57170/559dw"},
{"image": "91av.png", "name": "91av", "url": "https://9f8.anlnoejg.xyz/chan-8644/aff-hA2Rw"},
{"image": "91aw.png", "name": "91暗网", "url": "https://2d907.mfhgcphr.cc/aff-a78tR"},
{"image": "91重口.png", "name": "91重口", "url": "https://b12d6.wdbtleq.xyz/aff-eNmGs"},
{"image": "hsxs.png", "name": " 好色先生", "url": "https://ef86.tsvuinyz.cc/chan/hs0175/bhZ3"},
{"image": "clsq.png", "name": " 草榴社区", "url": "https://9dd3.mwtaahkv.xyz/aff-a4phK"},
{"image": "crks.png", "name": "成人快手", "url": "https://f027.slvotrt.cc/chan/ksh0518/edkU"},
{"image": "dy.png", "name": " 抖阴Proj", "url": "https://cb60.ywbnjet.xyz/chan-2588/aff-aZYFa"},
{"image": "gili.png", "name": " GiliGili", "url": "https://cce5.wsgxyaiq.xyz/chan/bu0891/66Ma"},
{"image": "hj.png", "name": "海角社区b", "url": "https://f27b.fvnfqdhf.cc/chan/hjapp0141/BSFS"},
{"image": "hls.png", "name": " 黑料社", "url": "https://c88c7.hdxcmozn.cc/aff-Dtsn"},
{"image": "md.png", "name": "麻豆视频", "url": "https://4af.xtrkkli.xyz/aff-CubX"},
{"image": "s.png", "name": " soul", "url": "https://f09d.keexxtg.xyz/aff-pPBh"},
{"image": "sgp.png", "name": "水果派", "url": "https://52f0.wwpjyklm.xyz/chan/GS0782/kEC6"},
{"image": "wmq.png", "name": " 微密圈", "url": "https://07a.vmdicjn.xyz/chan-1876/aff-arDtH"},
{"image": "wwtt.png", "name": " 外网天堂", "url": "https://e2c94.kfhzajh.xyz/aff-and6C"},
{"image": "xb.png", "name": "杏吧", "url": "https://ee854.xonxqcso.xyz/aff-bqTTQ"},
{"image": "xz.png", "name": " xvideo", "url": "https://1bb.gpvbunl.cc/chan/xv0022/cH5F"},
{"image": "myfq.png", "name": "蚂蚁翻墙", "url": "https://063.barrtaq.cc/c-18844/a-bSDAu"}
]
