const sites = [
  { "image": "tiktok.gif",     "name": "TikTok成人版",     "url": "https://tpv10.cc" },
  { "image": "txvlog.gif",     "name": "糖心vlog",         "url": "https://woh02szd.brovakbblavryc8lnvikrilvax.com/hy/41398/6agtrtx" },
  { "image": "jmtt.gif",       "name": "禁漫天堂",         "url": "https://47d.cmmyrgs.top/chan/jm1300/5rmW" },
  { "image": "hjllsq.gif",     "name": "海角乱伦社区",      "url": "https://436b.sasmnpbo.org/aff-ekUuZ"},
  { "image": "bkmh.gif",       "name": "哔咔漫画",         "url": "https://adh.drakilstorvryc8jvaxplidro.com/hy/41396/arq19bk" },
  { "image": "91qy.png",       "name": "91妻友",           "url": "https://9f3.hizbqor.cc/aff-cfHS7" },
  { "image": "51dm.gif",       "name": "51动漫",           "url": "https://45c3.sjymcsjw.cc/?code=bJMDj&c=18844" },
  { "image": "Pornhub.gif",    "name": "PornHub",          "url": "https://984.gzwgglu.top/chan/GS1000/agtRG" },
  { "image": "51mh2.gif",      "name": "51漫画",           "url": "https://woh03szd.fylslovryc8lntekorfarnik.com/ck/41400/xeumh" },
  { "image": "hj.gif",         "name": "海角社区",        "url": "https://woh03szd.xurtsnovryc8lrvakadrumbek.com/hy/41402/g1uhjsq" },
  { "image": "xxb.png",         "name": "杏吧",             "url": "https://woh04szd.fentdrovryc8lfakrozibrek.com/ky/41504/iq1gybxb" },
  { "image": "xnjlb.gif",      "name": "小蓝俱乐部",       "url": "https://2fa5.scsubbu.org/chan/xb3859/czTvz" },
  { "image": "91dsp.png",      "name": "91短视频",         "url": "https://6ce4.erbrqsbi.org/chan-5028/aff-mhY87" },
  { "image": "91porn.png",     "name": "91PORN",           "url": "https://5983.uhgtjzs.cc/chan/GS0710/nN9s" },
  { "image": "awjq.png",       "name": "暗网禁区",         "url": "https://f8e.tdagmco.com/aff-dHXe9" },
  { "image": "dymax.gif",      "name": "抖音Max",          "url": "https://acc3.cleqzvf.cc/chan/max1559/KD4j" },
  { "image": "pilipili.png",   "name": "pilipili二次元",   "url": "https://771.cwqdidqk.org/?code=arGSB&c=18844" },
  { "image": "clsq.png",       "name": "草榴社区",         "url": "https://5a5e.gvvjxmo.top/aff-a4phK" },
  { "image": "51pc.png",       "name": "51品茶",           "url": " https://920c.scwtwauq.org/?code=bqgkF&c=18844" },
  { "image": "bld.gif",       "name": "不撸帝",           "url": "https://uzhgfe.obiv6wlf97aw.vip/blued-6umibld" },
];
