const sites = [
  { "image": "https://picsislkss.1031.academy/i/2025/08/16/71a41259cd301ecc92f019d6d83c06d2e7d9d7e9.gif",     "name": "星星直播",     "url": "https://dspern8asx.xdslkajb100850029.top:57009/1_xxzb/et.htm?yxn847" },
  { "image": "bkmh.gif",       "name": "哔咔漫画",         "url": "https://b2743.el7x1ptm2b73.vip?ch=arq19bk" },
  { "image": "txvlog.gif",     "name": "糖心vlog",         "url": "https://bjc.jorlakstornpyzvryc7srekil.com/hy/41398/6agtrtx" },
  { "image": "jmtt.gif",       "name": "禁漫天堂",         "url": "https://d2f2c.cmmyrgs.top/chan/jm1300/5rmW" },
  { "image": "hjllsq.gif",     "name": "海角乱伦社区",      "url": "https://efa1.vcofhfwr.com/aff-ekUuZ"},
  { "image": "tiktok.gif",     "name": "TikTok成人版",     "url": "https://tpv10.cc" },
  { "image": "lld.gif",       "name": "萝莉岛",             "url": "https://a38.facmbvb.top/chan/lldapp0875/F9ac" },
  { "image": "51dm.gif",       "name": "51动漫",           "url": "https://856a.uraemig.top/?code=bJMDj&c=18844" },
  { "image": "Pornhub.gif",    "name": "PornHub",          "url": "https://4de.giuvmxiq.top/chan/GS1000/agtRG" },
  { "image": "51mh2.gif",      "name": "51漫画",           "url": "https://dd9018.fylglivryc7mmboorstornil.com/ck/41400/xeumh" },
  { "image": "hj.gif",         "name": "海角社区",        "url": "https://dd9018.drazelbluvzolvryc7mpekon.com/hy/41402/g1uhjsq" },
  { "image": "xxb.png",         "name": "杏吧",             "url": "https://dd9018.kravlismozhevryc7mntorrvik.com/ky/41504/iq1gybxb" },
  { "image": "xnjlb.gif",      "name": "小蓝俱乐部",       "url": "https://9470.scsubbu.org/chan/xb3859/czTvz" },
  { "image": "btcy.gif",       "name": "半糖次元",           "url": "https://dd9018.jankruvryc7mlbodorvornux.com/bk/42916/p51rbtcy" },
  { "image": "sssm.gif",       "name": "绳师SM",           "url": "https://ccd23.wrakruvryc7olbomboplixom.com/mk/42914/yj1gsssm" },
  { "image": "91qy.png",       "name": "91妻友",           "url": "https://2f2c.vefjogzx.cc/aff-cfHS7" },
  { "image": "91dsp.png",      "name": "91短视频",         "url": "https://e8e5.tulojsis.top/chan-5028/aff-mhY87" },
  { "image": "91porn.png",     "name": "91PORN",           "url": "https://e5c5.vbdiing.top/chan/GS0710/nN9s" },
  { "image": "awjq.png",       "name": "暗网禁区",         "url": " https://40ef.vcqhmjq.cc/aff-dHXe9" },
  { "image": "dymax.gif",      "name": "抖音Max",          "url": "https://36f6.vjkvfpng.cc/chan/max1559/KD4j" },
  { "image": "pilipili.png",   "name": "pilipili二次元",   "url": "https://0db4.cwqdidqk.org/?code=arGSB&c=18844" },
  { "image": "clsq.png",       "name": "草榴社区",         "url": " https://f16.gvvjxmo.top/aff-a4phK" },
  { "image": "51pc.png",       "name": "51品茶",           "url": " https://f5b.scwtwauq.org/?code=bqgkF&c=18844" },
  { "image": "bld.gif",        "name": "不撸帝",           "url": "https://dd9018.drazelbluvzolvryc7mpekon.com/ck/41394/6umibld" },
  { "image": "crks.png",       "name": "成人快手",         "url": "https://7dd1.vdfrpfh.org/chan/ksh0518/edkU" },
  { "image": "91aw.png",       "name": "91暗网",           "url": "https://9a7f4.mukzwgk.cc/aff-a78tR" },
  { "image": "91重口.png",     "name": "91重口",           "url": "https://e07.itvrzgx.cc/aff-eNmGs"},
  { "image": "aiss.png",       "name": "ai色色",          "url": "https://960e.ouatena.top/aff-JCVd" },
  { "image": "wwtt.png",       "name": "外网天堂",           "url": "https://4e34.ttsumfo.com/aff-and6C" },
  { "image": "ttt.png",        "name": "汤头条",           "url": "https://57ab.hrfthnnq.cc/chan/a15235/jxTf3" },
  { "image": "sgp.png",        "name": "水果派",           "url": "https://cedfb.daokzgc.org/chan/GS0782/kEC6" },
  { "image": "hls.png",        "name": "黑料社",           "url": "https://34153.rkwwubx.top/aff-Dtsn" },
  { "image": "50dh.png",       "name": "50度灰",           "url": "https://f0e14.hpmlbxl.cc/chan/h57170/559dw" },
  
  { "image": "91ym.jpg",       "name": "91淫母",             "url": "https://ivrb.es14t.com/mcg/?channel=ppkccI" },
  { "image": "17s.jpg",        "name": "17岁",             "url": "https://nhpb.14glj.com/dzy/?channel=erxlPr" },
  { "image": "llsq.jpg",        "name": "乱伦社区",          "url": "https://fgob.d378v.com/pbn/?channel=R1lPfj" },
  { "image": "91xy.jpg",        "name": "91学院",           "url": "https://clwb.ju9an.com/mzi/?channel=GDpG1x" },
  { "image": "lyd.jpg",        "name": "萝莉岛",           "url": "https://caqb.sm6du.com/cox/?channel=qTFeUe" },
  { "image": "xlq.jpg",        "name": "新娘圈",           "url": "https://cikb.3j3or.com/ifx/?channel=Z3f6hwe" },
];
