const sites = [
  { "image": "tiktok.gif",     "name": "TikTok成人版",     "url": "https://tpv10.cc" },
  { "image": "txvlog.gif",     "name": "糖心vlog",         "url": "https://woh02szd.brovakbblavryc8lnvikrilvax.com/hy/41398/6agtrtx" },
  { "image": "jmtt.gif",       "name": "禁漫天堂",         "url": "https://0eae.fjmzqbeg.top/chan/jm1300/5rmW" },
  { "image": "hjllsq.gif",     "name": "海角乱伦社区",      "url": "https://f98c1.jymnnqr.top/aff-ekUuZ"},
  { "image": "bkmh.gif",       "name": "哔咔漫画",         "url": "https://woh03szd.xurtaglivryc8lmbodravex.com/hy/41396/arq19bk" },
  { "image": "91qy.png",       "name": "91妻友",           "url": "https://ad1.lpgylbv.com/aff-cfHS7" },
  { "image": "51dm.gif",       "name": "51动漫",           "url": "https://f216.aefvxkm.cc/?code=bJMDj&c=18844" },
  { "image": "Pornhub.gif",    "name": "PornHub",          "url": "https://8748.wgfgdgs.top/chan/GS1000/agtRG" },
  { "image": "51mh2.gif",      "name": "51漫画",           "url": "https://woh03szd.fylslovryc8lntekorfarnik.com/ck/41400/xeumh" },
  { "image": "hj.png",         "name": "海角社区",        "url": "https://woh03szd.xurtsnovryc8lrvakadrumbek.com/hy/41402/g1uhjsq" },
  { "image": "xxb.png",         "name": "杏吧",             "url": "https://woh04szd.fentdrovryc8lfakrozibrek.com/ky/41504/iq1gybxb" },
  { "image": "aiss.png",       "name": "ai色色",           "url": "https://7487.zwwqedt.top/aff-JCVd" },
  { "image": "91dsp.png",      "name": "91短视频",         "url": "https://c355.hazuscs.cc/chan-5028/aff-mhY87" },
  { "image": "91porn.png",     "name": "91PORN",           "url": "https://8d30.eotiiye.cc/chan/GS0710/nN9s" },
  { "image": "awjq.png",       "name": "暗网禁区",         "url": "https://2c0e9.abyrzgl.top/aff-dHXe9" },
  { "image": "dymax.gif",      "name": "抖音Max",          "url": "https://80a16.kbyxzbxd.com/chan/max1559/KD4j" },
  { "image": "pilipili.png",   "name": "pilipili二次元",   "url": "https://a09.ndejhjt.cc/?code=arGSB&c=18844" },
  { "image": "xnjlb.gif",      "name": "小蓝俱乐部",       "url": "https://fdb.afwemnw.space/chan/xb3859/czTvz" },
  { "image": "clsq.png",       "name": "草榴社区",         "url": "https://a62b.zymnvro.top/aff-a4phK" },
  { "image": "51pc.png",       "name": "51品茶",           "url": "https://d076.fokkpsdq.top/?code=bqgkF&c=18844" },
];
